capdemo/urls.py
from django.urls import path

from . import views

app_name = 'capdemo'
urlpatterns = [
    path('', views.index, name='index'),
    path('caption/', views.caption_all, name='results')
]

demosite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('capdemo/', include('capdemo.urls'))
]

capdemo/models.py
from django.db import models

# Create your models here.

capdemo/views.py
from django.shortcuts import render

# Create your views here.
from PIL import Image
import torchvision
from io import BytesIO
import os.path as oph
import imquality.brisque as brisque

from .caption_me import cap_example

def index(request):
    context = {}
    return render(request, 'capdemo/index.html', context)


def caption_all(request):

    img_file = request.FILES['fileUpload']
    file_name = img_file.name
    img_bytes = img_file.read()
    x = Image.open(BytesIO(img_bytes)).convert('RGB')
    im_quality = brisque.score(x)
    context = {'im_quality': '{:.2f}'.format(im_quality)}

    if im_quality > 50.0:
        context['no_caption'] = True
    else:
        context['no_caption'] = False 
        x = x.resize((224, 224))
        x = torchvision.transforms.ToTensor()(x)
        x = torchvision.transforms.Normalize(mean = [ 0.485, 0.456, 0.406 ], std = [ 0.229, 0.224, 0.225 ])(x)
        context.update(cap_example(x))
        with open(oph.join(oph.dirname(__file__), 'static/capdemo/images/{}'.format(file_name)), 'wb') as f:
            f.write(img_bytes)
    context['filename'] = file_name
    return render(request, 'capdemo/results.html', context)

capdemo/templates/capdemo/index.html
<!DOCTYPE html>
<html>

<head>
  <title>
    caption
  </title>
  {% load static %}

  <link rel="styleSheet" href="{% static 'capdemo/style.css'%}" type="text/css">
</head>

<body>
  <h2>File Upload & Image Preview</h2>
  <p class="lead">No Plugins <b>Just Javascript</b></p>

  <!-- Upload  -->
  <form id="file-upload-form" class="uploader" action="{% url 'capdemo:results' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input id="file-upload" type="file" name="fileUpload" accept="image/*" />

    <label for="file-upload" id="file-drag">
      <img id="file-image" src="#" alt="Preview" class="hidden">
      <div id="start">
        <i class="fa fa-download" aria-hidden="true"></i>
        <div>点击这里选择图片</div>
        <div id="notimage" class="hidden">Please select an image</div>
        <span id="file-upload-btn" class="btn btn-primary">选择图片</span>
      </div>
      <div id="response" class="hidden">
        <div id="messages"></div>
        <progress class="progress" id="file-progress" value="0">
          <span>0</span>%
        </progress>
      </div>
    </label>
    <input type="submit" class="btn btn-primary" value="提交" />
  </form>

</body>

<script src="{% static 'capdemo/script.js' %}"></script>
</html>

capdemo/templates/capdemo/results.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <title>结果</title>
    <style type="text/css">
        .all {
            width: 800px;
            min-height: 800px;
            margin: 30px auto;
            border: 1px solid brown;
            padding: 20px;
            text-align: center;
        }
    </style>
    {% load static %}
</head>

<body>
    <div class="all">
        <h1>结果展示</h1>
        <img src="{% static 'capdemo/images/' %}{{filename}}" />
        <p><i>图像质量</i>:<b>{{im_quality}}</b>(分数越小质量越高)</p>
        {% if no_caption %}
        <p>图像质量过低，不适于图像描述。详情见<a href="https://learnopencv.com/image-quality-assessment-brisque/" target="_blank">了解更多</a></p>
        {% else %}
        <p>{{caption_zh}}</p>
        <p>{{caption_en}}</p>
        {% endif %}
    </div>
</body>

</html>